name: AppSec Scans 2

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main", "feature/*" ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  
jobs:
  AppSec-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: cxone scan
        uses: my-test-1234/cxone-custom-action@main
        with:
          cx_tenant: ${{ secrets.CX_TENANT }}
          base_uri: ${{ secrets.BASE_URI }}
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
      - name: Print Sarif
        run: cat cx_result.sarif
      # - name: Generate bypass.sarif file
      #   run: |
      #     echo '{"$schema":"https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json","version":"2.1.0","runs":[{"tool":{"driver":{"name":"Checkmarx One","version":"1.0","informationUri":"https://checkmarx.com/resource/documents/en/34965-67042-checkmarx-one.html","rules":[]}},"results":[]}]}'> cx_result.sarif

      # - name: Upload SARIF file
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: cx_result.sarif
